Tested

diff --git a/compileLibs b/compileLibs
--- a/compileLibs
+++ b/compileLibs
@@ -1,5 +1,14 @@
 #!/bin/bash
-# This file compiles libArgumentParser.so
+# This file compiles libArgumentParser.so & libUtil
+
+verifyLibInstalled() {
+	ldconfig -p | grep $1 > /dev/null
+	exitCode=$?
+
+	[ $exitCode = 0 ] && echo "Success!	"
+	[ $exitCode = 1 ] && echo "An error occured."
+
+}
 
 if [ -d build ]; then
 	echo "Already existing folder named \`build\` found."
@@ -26,6 +35,7 @@ if [ -d build ]; then
 			mv build "_build ($count)"
 			echo "folder renamed to \`_build ($count)\`."
 		fi
+		mkdir build
 	elif [ $ans = 'e' ]; then
 		rm -rf build/* && echo "folder erased."
 	elif [ $ans = 'o' ]; then
@@ -34,25 +44,27 @@ if [ -d build ]; then
 		echo "You just found a bug!"
 		exit 2
 	fi
-else
+	cd build
+elif [[ $(pwd) != */build ]]; then
 	mkdir build
+	cd build
 fi
-cd build
 
 cmake .. && cmake --build .
 if [[ $? = 0 && "$1" = "--install" ]]; then
 	echo -e "\\nRequiring root permission in order to copy libArgumentParser.so into /usr/lib and running ldconfig."
-	sudo cp libArgumentParser.so /usr/lib/libArgumentParser.so && sudo ldconfig /usr/lib/
+	sudo cp libArgumentParser.so /usr/lib/libArgumentParser.so	&& sudo ldconfig /usr/lib/
+	sudo cp libUtil.so /usr/lib/libUtil.so 						&& sudo ldconfig /usr/lib/
 	
-	ldconfig -p | grep libArgumentParser\\.so > /dev/null
-	[ $? = 0 ] && echo "Success!	"
-	[ $? = 1 ] && echo "An error occured."
+	verifyLibInstalled "libArgumentParser\\.so"
+	verifyLibInstalled "libUtil\\.so"
 
 	echo -e "\\nCopying Parser.hpp..."
 	! [ -d "/usr/include/c++/nlibs" ] && sudo mkdir /usr/include/c++/nlibs
 	sudo cp ../Parser.hpp /usr/include/c++/nlibs/Parser && echo "Success!	"
+	sudo cp ../Util.hpp /usr/include/c++/nlibs/Util && echo "Success!	"
 	
-	! [ -L /usr/include/nlibs ] && sudo ln -s /usr/include/c++/nlibs /usr/include/nlibs
 	# if nlibs if a file but not a symlink, it will print an error
+	! [ -L /usr/include/nlibs ] && sudo ln -s /usr/include/c++/nlibs /usr/include/nlibs
 fi
 echo "done"
